### ISSUE TITLE
Docker Compose

### ISSUE THREAD

**Issue by sachinkbansal** [cuebook/CueObserve#137]

**Comment by kshitij-cuebook** [comment]
The dockerfiles of CueObserve are too big and takes a lot of time to build. This I think is even a more important issue than adding features, because it seems to restrict the usability. 

Additionally, the structure of dockerfile is such that it build everytime, even if there is no change at all. I think we should properly create the dockerfile again, and separate the dockerfile for backend and ui.

We can discuss this in detail over a call.
